

export const

OCTAVE_LENGTH = 7,

NUMBER_OF_FULL_OCTAVES = 7,

CORNERS_RADIUS = 2,

KEY_PADDING = 2,
KEY_HALF_PADDING = KEY_PADDING / 2,

SHADOW_OFFSET = 2,

KEY_WHITE_WIDTH = 30,
KEY_WHITE_OUTER_WIDTH = KEY_WHITE_WIDTH + KEY_PADDING,
KEY_WHITE_HEIGHT = 175,
KEY_WHITE_SUB_HEIGHT = 65,

NUMBER_OF_CONTENT_KEYS = 14, // from Tilde to BackspaceKey and from Tab to Enter
PIANO_CONTENT_WIDTH = NUMBER_OF_CONTENT_KEYS * KEY_WHITE_WIDTH,
PIANO_CONTENT_HEIGHT = KEY_WHITE_HEIGHT + KEY_PADDING + SHADOW_OFFSET

;
